/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customers */
        get: operations["customers_api_v1_customers_get"];
        put?: never;
        /** Create Customer */
        post: operations["create_customer_api_v1_customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customer */
        get: operations["customer_api_v1_customers__customer_id__get"];
        put?: never;
        post?: never;
        /** Archive Customer */
        delete: operations["archive_customer_api_v1_customers__customer_id__delete"];
        options?: never;
        head?: never;
        /** Update Customer */
        patch: operations["update_customer_api_v1_customers__customer_id__patch"];
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_customers__customer_id__projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project */
        get: operations["project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Project */
        post: operations["archive_project_api_v1_projects__project_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/dialogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace */
        get: operations["workspace_api_v1_projects__project_id__dialogue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create */
        post: operations["create_api_v1_projects__project_id__conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_conversations__conversation_id__messages_get"];
        put?: never;
        /** Send */
        post: operations["send_api_v1_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/clarifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Questions */
        get: operations["questions_api_v1_projects__project_id__clarifications_get"];
        put?: never;
        /** Generate */
        post: operations["generate_api_v1_projects__project_id__clarifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clarifications/{question_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["answer_api_v1_clarifications__question_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clarifications/{question_id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip */
        post: operations["skip_api_v1_clarifications__question_id__skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_v1_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memories */
        get: operations["memories_api_v1_projects__project_id__memories_get"];
        put?: never;
        /** Create Memory */
        post: operations["create_memory_api_v1_projects__project_id__memories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memories/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Memory */
        delete: operations["delete_memory_api_v1_memories__memory_id__delete"];
        options?: never;
        head?: never;
        /** Edit Memory */
        patch: operations["edit_memory_api_v1_memories__memory_id__patch"];
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Conversation */
        post: operations["reset_conversation_api_v1_conversations__conversation_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/memories/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Project */
        post: operations["reset_project_api_v1_projects__project_id__memories_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Message */
        get: operations["source_message_api_v1_messages__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Documents */
        get: operations["documents_api_v1_documents_get"];
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document */
        get: operations["document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chunks */
        get: operations["chunks_api_v1_documents__document_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_v1_documents__document_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex */
        post: operations["reindex_api_v1_documents__document_id__reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable */
        post: operations["disable_api_v1_documents__document_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_v1_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/retrieval/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrieval */
        post: operations["retrieval_api_v1_retrieval_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_v1_projects__project_id__requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit */
        patch: operations["edit_api_v1_projects__project_id__requirements_patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/requirements/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: operations["confirm_api_v1_projects__project_id__requirements_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/requirements/extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract */
        post: operations["extract_api_v1_projects__project_id__requirements_extractions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/requirements/extractions/{extraction_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_projects__project_id__requirements_extractions__extraction_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerInput */
        AnswerInput: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Answer */
            answer: string;
            /** Version */
            version: number;
            /** Profile Version */
            profile_version: number;
            /** Epoch */
            epoch: number;
        };
        /** Body_upload_api_v1_documents_post */
        Body_upload_api_v1_documents_post: {
            /** File */
            file: string;
            /** Scope */
            scope: string;
            /** Customer Id */
            customer_id?: string | null;
            /** Project Id */
            project_id?: string | null;
        };
        /** ChunkList */
        ChunkList: {
            /** Items */
            items: components["schemas"]["ChunkView"][];
            /** Next Offset */
            next_offset: number | null;
        };
        /** ChunkView */
        ChunkView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Ordinal */
            ordinal: number;
            /** Generation */
            generation: number;
            /** Content */
            content: string;
            /** Token Count */
            token_count: number | null;
            /** Page Number */
            page_number: number | null;
            /** Section Path */
            section_path: string[];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** ClarificationView */
        ClarificationView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Category */
            category: string;
            /** Question */
            question: string;
            /** Reason */
            reason: string;
            /** Importance */
            importance: string;
            /** Status */
            status: string;
            /** Answer */
            answer: string | null;
            /** Source Message Id */
            source_message_id: string | null;
            /** Version */
            version: number;
        };
        /** ConfirmInput */
        ConfirmInput: {
            /** Version */
            version: number;
        };
        /** ConversationInput */
        ConversationInput: {
            /**
             * Title
             * @default 需求澄清
             */
            title: string;
        };
        /** ConversationView */
        ConversationView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Epoch */
            epoch: number;
        };
        /** CustomerCreate */
        CustomerCreate: {
            /** Name */
            name: string;
            /**
             * Industry
             * @default
             */
            industry: string;
            /**
             * Region
             * @default
             */
            region: string;
            /**
             * Company Size
             * @default
             */
            company_size: string;
            /** Profile */
            profile?: {
                [key: string]: unknown;
            };
        };
        /** CustomerOut */
        CustomerOut: {
            /** Name */
            name: string;
            /**
             * Industry
             * @default
             */
            industry: string;
            /**
             * Region
             * @default
             */
            region: string;
            /**
             * Company Size
             * @default
             */
            company_size: string;
            /** Profile */
            profile?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Version */
            version: number;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CustomerPage */
        CustomerPage: {
            /** Items */
            items: components["schemas"]["CustomerOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CustomerUpdate */
        CustomerUpdate: {
            /** Name */
            name?: string | null;
            /** Industry */
            industry?: string | null;
            /** Region */
            region?: string | null;
            /** Company Size */
            company_size?: string | null;
            /** Profile */
            profile?: {
                [key: string]: unknown;
            } | null;
            /** Version */
            version: number;
        };
        /** DocumentList */
        DocumentList: {
            /** Items */
            items: components["schemas"]["DocumentView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** DocumentView */
        DocumentView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Customer Id */
            customer_id: string | null;
            /** Project Id */
            project_id: string | null;
            /** Scope */
            scope: string;
            /** Title */
            title: string;
            /** Source Type */
            source_type: string;
            /** Mime Type */
            mime_type: string;
            /** Sha256 */
            sha256: string;
            /** Status */
            status: string;
            /** Generation */
            generation: number;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            job?: components["schemas"]["JobView"] | null;
        };
        /** EditInput */
        EditInput: {
            /** Version */
            version: number;
            /** Item Id */
            item_id?: string | null;
            item?: components["schemas"]["ItemInput"] | null;
            /** Status */
            status?: ("confirmed" | "rejected") | null;
            /** Summary */
            summary?: string | null;
            /** Resolve With */
            resolve_with?: ("keep" | "replace") | null;
        };
        /** Evidence */
        Evidence: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Page Number */
            page_number: number | null;
            /** Section Path */
            section_path: string[];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Generation */
            generation: number;
            /** Scope */
            scope: string;
            /** Score */
            score: number;
            /** Ranks */
            ranks: {
                [key: string]: number;
            };
        };
        /** ExtractionInput */
        ExtractionInput: {
            /**
             * Text
             * @default
             */
            text: string;
            /** Document Ids */
            document_ids?: string[];
        };
        /** ExtractionView */
        ExtractionView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Error Message */
            error_message: string | null;
            /** Model Info */
            model_info: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthReport */
        HealthReport: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Services */
            services: {
                [key: string]: "ok" | "unavailable";
            };
        };
        /** HistoryView */
        HistoryView: {
            conversation: components["schemas"]["ConversationView"];
            /** Messages */
            messages: components["schemas"]["MessageView"][];
            /** Next After */
            next_after: number | null;
            run: components["schemas"]["RunView"] | null;
        };
        /** ItemInput */
        ItemInput: {
            /**
             * Category
             * @enum {string}
             */
            category: "background" | "pain_point" | "goal" | "functional" | "non_functional" | "integration" | "data" | "security_compliance" | "constraint" | "timeline_budget" | "acceptance_metric" | "risk";
            /** Title */
            title: string;
            /** Content */
            content: string;
            /**
             * Priority
             * @default unknown
             * @enum {string}
             */
            priority: "must" | "should" | "could" | "unknown";
        };
        /** ItemView */
        ItemView: {
            /**
             * Category
             * @enum {string}
             */
            category: "background" | "pain_point" | "goal" | "functional" | "non_functional" | "integration" | "data" | "security_compliance" | "constraint" | "timeline_budget" | "acceptance_metric" | "risk";
            /** Title */
            title: string;
            /** Content */
            content: string;
            /**
             * Priority
             * @default unknown
             * @enum {string}
             */
            priority: "must" | "should" | "could" | "unknown";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "confirmed" | "rejected" | "conflicted";
            /** Confidence */
            confidence: number | null;
            /** Sources */
            sources: components["schemas"]["SourceView"][];
            /** Edited */
            edited: boolean;
            /** Conflicts With */
            conflicts_with: string[];
        };
        /** JobView */
        JobView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Resource Id
             * Format: uuid
             */
            resource_id: string;
            /** Job Type */
            job_type: string;
            /** Resource Type */
            resource_type: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Attempts */
            attempts: number;
            /** Generation */
            generation: number;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MemoryEdit */
        MemoryEdit: {
            /** Version */
            version: number;
            /** Content */
            content: string;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "confirmed" | "expired";
            /** Expires At */
            expires_at?: string | null;
        };
        /** MemoryInput */
        MemoryInput: {
            /**
             * Source Message Id
             * Format: uuid
             */
            source_message_id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "conversation" | "project" | "customer";
            /**
             * Kind
             * @default fact
             * @enum {string}
             */
            kind: "fact" | "preference" | "decision" | "constraint" | "summary";
            /** Content */
            content: string;
        };
        /** MemoryView */
        MemoryView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scope */
            scope: string;
            /** Kind */
            kind: string;
            /** Content */
            content: string;
            /**
             * Source Message Id
             * Format: uuid
             */
            source_message_id: string;
            /** Conversation Id */
            conversation_id: string | null;
            /** Status */
            status: string;
            /** Expires At */
            expires_at: string | null;
            /** Version */
            version: number;
        };
        /** MessageInput */
        MessageInput: {
            /** Text */
            text: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Epoch */
            epoch: number;
        };
        /** MessageView */
        MessageView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Seq */
            seq: number;
            /** Epoch */
            epoch: number;
            /** Role */
            role: string;
            /** Content */
            content: {
                [key: string]: unknown;
            }[];
            /** Run Id */
            run_id: string | null;
            /** Model Info */
            model_info: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProfileView */
        ProfileView: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Version */
            version: number;
            /** Summary */
            summary: string;
            /** Items */
            items: components["schemas"]["ItemView"][];
            /** Completeness Score */
            completeness_score: number;
            /** Missing Categories */
            missing_categories: string[];
            /** Confirmed At */
            confirmed_at: string | null;
            /** Writable */
            writable: boolean;
            extraction: components["schemas"]["ExtractionView"] | null;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /**
             * Owner User Id
             * Format: uuid
             */
            owner_user_id: string;
            /** Owner Display Name */
            owner_display_name: string;
            /** Status */
            status: string;
            /** Version */
            version: number;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectPage */
        ProjectPage: {
            /** Items */
            items: components["schemas"]["ProjectOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Version */
            version: number;
        };
        /** ResetInput */
        ResetInput: {
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
        };
        /** RunView */
        RunView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Model Info */
            model_info: {
                [key: string]: unknown;
            };
            /** Error Message */
            error_message: string | null;
        };
        /** SearchInput */
        SearchInput: {
            /** Query */
            query: string;
            /** Customer Id */
            customer_id?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** Scopes */
            scopes?: ("organization" | "customer" | "project")[];
            /** Mime Types */
            mime_types?: string[];
            /** Tags */
            tags?: string[];
            /**
             * Top K
             * @default 8
             */
            top_k: number;
            /**
             * Candidates
             * @default 20
             */
            candidates: number;
            /**
             * Document Share
             * @default 0.4
             */
            document_share: number;
        };
        /** SearchResult */
        SearchResult: {
            /** Query */
            query: string;
            /** Profile */
            profile: string;
            /** Items */
            items: components["schemas"]["Evidence"][];
        };
        /** SourceView */
        SourceView: {
            /** Source Id */
            source_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "document" | "user" | "message";
            /** Quote */
            quote: string;
            /** Message Seq */
            message_seq?: number | null;
            /** Message Id */
            message_id?: string | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Document Id */
            document_id?: string | null;
            /** Title */
            title: string;
            /** Generation */
            generation?: number | null;
            /** Page Number */
            page_number?: number | null;
            /** Section Path */
            section_path?: string[];
            /** Line Start */
            line_start?: number | null;
            /** Line End */
            line_end?: number | null;
        };
        /** UploadView */
        UploadView: {
            document: components["schemas"]["DocumentView"];
            job: components["schemas"]["JobView"];
            /** Duplicate */
            duplicate: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionInput */
        VersionInput: {
            /** Version */
            version: number;
        };
        /** WorkspaceView */
        WorkspaceView: {
            /** Conversations */
            conversations: components["schemas"]["ConversationView"][];
            /** Clarifications */
            clarifications: components["schemas"]["ClarificationView"][];
            /** Memories */
            memories: components["schemas"]["MemoryView"][];
            /** Writable */
            writable: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    customers_api_v1_customers_get: {
        parameters: {
            query?: {
                limit?: number;
                after?: string | null;
                archived?: boolean;
            };
            header: {
                "x-organization-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_customer_api_v1_customers_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    customer_api_v1_customers__customer_id__get: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_customer_api_v1_customers__customer_id__delete: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_customer_api_v1_customers__customer_id__patch: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_customers__customer_id__projects_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_api_v1_projects_get: {
        parameters: {
            query?: {
                limit?: number;
                after?: string | null;
                archived?: boolean;
                customer_id?: string | null;
            };
            header: {
                "x-organization-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_project_api_v1_projects__project_id__archive_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_api_v1_projects__project_id__dialogue_get: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_projects__project_id__conversations_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header: {
                "x-organization-id": string;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_api_v1_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    questions_api_v1_projects__project_id__clarifications_get: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_v1_projects__project_id__clarifications_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_api_v1_clarifications__question_id__answer_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_api_v1_clarifications__question_id__skip_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_v1_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header: {
                authorization: string;
                "last-event-id"?: string | null;
                "x-organization-id": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memories_api_v1_projects__project_id__memories_get: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_memory_api_v1_projects__project_id__memories_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_api_v1_memories__memory_id__delete: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_memory_api_v1_memories__memory_id__patch: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_conversation_api_v1_conversations__conversation_id__reset_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_project_api_v1_projects__project_id__memories_reset_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_message_api_v1_messages__message_id__get: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    documents_api_v1_documents_get: {
        parameters: {
            query?: {
                scope?: ("organization" | "customer" | "project") | null;
                customer_id?: string | null;
                project_id?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header: {
                "x-organization-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_v1_documents_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v1_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chunks_api_v1_documents__document_id__chunks_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header: {
                "x-organization-id": string;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_v1_documents__document_id__download_get: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_api_v1_documents__document_id__reindex_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_api_v1_documents__document_id__disable_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_v1_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieval_api_v1_retrieval_search_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_api_v1_projects__project_id__requirements_get: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_api_v1_projects__project_id__requirements_patch: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_v1_projects__project_id__requirements_confirm_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_api_v1_projects__project_id__requirements_extractions_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_projects__project_id__requirements_extractions__extraction_id__cancel_post: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
            };
            path: {
                project_id: string;
                extraction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
}
