"""Private object operations. Keys are generated by the application, never supplied by clients."""

from contextlib import closing

from solution_copilot.config import get_settings
from solution_copilot.infrastructure.health import s3_client


def put_original(key: str, data: bytes, mime: str):
    with closing(s3_client()) as client:
        client.put_object(Bucket=get_settings().s3_bucket, Key=key, Body=data, ContentType=mime)


def read_original(key: str) -> bytes:
    with closing(s3_client()) as client:
        response = client.get_object(Bucket=get_settings().s3_bucket, Key=key)
        with closing(response["Body"]) as body:
            data = body.read(get_settings().upload_max_bytes + 1)
    if len(data) > get_settings().upload_max_bytes:
        raise ValueError("Object exceeds upload limit")
    return data


def delete_original(key: str):
    with closing(s3_client()) as client:
        client.delete_object(Bucket=get_settings().s3_bucket, Key=key)
